name: wm01
channels:
  - conda-forge
dependencies:
  - python=3.8.3
  - notebook=6.0.3
  - mkl-service=2.3.0
  - jupyterhub=1.1.0
  - numpy=1.18.5
  - matplotlib=3.2
  - pandas=1.0.5
  - scipy=1.5.0
  - pymc3=3.9.2
  - seaborn=0.10.1
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.2
  - scikit-image=0.17.2
  - scikit-learn=0.23.1
  # - graphviz=2.42.3
  - nose=1.3.7
  - arviz=0.9
  - pip=20.1.1
  - biopython=1.77
  - requests=2.24.0
  - pyyaml=5.3.1
  - scikit-learn-extra=0.1.0b2
  - pip:
      - adskalman==0.3.11
      # - dabest==0.3
      # - showast==0.2.4
